### ISSUE TITLE
BSI: generate metanorma.yml  for collections

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mnconvert#357]
Example for `bs-en-iso-13485-2016-a11-2021`:

[metanorma.yml]
```
---
metanorma:
  source:
    files:
      - iso-13485.adoc
      - en-iso-13485.adoc
      - bs-en-iso-13485.adoc

  collection:
    name: BS EN ISO 13485
    organization: The British Standards Institution
```
